var K=this.K||{};K.Resource=K.Resource||{};K.error=function(a,b){b=b||Error;throw new b(a);};K.global=this;K.log=function(){if(K.__debug&&K.Env.IS_DEV)if("console"in window&&"log"in window.console){var a=arguments.length;if(a==1)window.console.log(arguments[0]);else a==2&&window.console.log(arguments[0],arguments[1])}else window.opera&&window.opera.postError&&window.opera.postError.apply(window.opera,arguments)};
K.error=function(){if(K.__debug&&K.Env.IS_DEV)if("console"in window&&"error"in window.console){var a=arguments.length;if(a==1)window.console.error(arguments[0]);else a==2&&window.console.error(arguments[0],arguments[1])}else window.opera&&window.opera.postError&&window.opera.postError.apply(window.opera,arguments)};

(function(e){var i=Array.prototype,l=i.slice,u=Object.prototype.hasOwnProperty,m=i.forEach,n=i.map,o=i.reduce,p=i.reduceRight,q=i.filter,r=i.every,s=i.some,j=i.indexOf,t=i.lastIndexOf,k={};e.forEach=function(a,c,b){if(a!=null)if(m&&a.forEach===m)a.forEach(c,b);else if(e.isNumber(a.length))for(var d=0,f=a.length;d<f;d++){if(c.call(b,a[d],d,a)==k)return}else for(d in a)if(u.call(a,d))if(c.call(b,a[d],d,a)===k)return};e.map=function(a,c,b){var d=[];if(a==null)return d;if(n&&a.map===n)return a.map(c,
b);e.forEach(a,function(f,g,h){d[d.length]=c.call(b,f,g,h)});return d};e.reduce=function(a,c,b,d){var f=b!==void 0;if(a==null)a=[];if(o&&a.reduce===o){if(d)c=e.bind(c,d);return f?a.reduce(c,b):a.reduce(c)}e.forEach(a,function(g,h,v){if(!f&&h===0){b=g;f=true}else b=c.call(d,b,g,h,v)});if(!f)throw new TypeError("Reduce of empty array with no initial value");return b};e.reduceRight=function(a,c,b,d){if(a==null)a=[];if(p&&a.reduceRight===p){if(d)c=e.bind(c,d);return b!==void 0?a.reduceRight(c,b):a.reduceRight(c)}a=
(e.isArray(a)?a.slice():e.toArray(a)).reverse();return e.reduce(a,c,b,d)};e.detect=function(a,c,b){var d;e.some(a,function(f,g,h){if(c.call(b,f,g,h)){d=f;return true}});return d};e.filter=function(a,c,b){var d=[];if(a==null)return d;if(q&&a.filter===q)return a.filter(c,b);e.forEach(a,function(f,g,h){if(c.call(b,f,g,h))d[d.length]=f});return d};e.every=function(a,c,b){var d=true;if(a==null)return d;if(r&&a.every===r)return a.every(c,b);e.forEach(a,function(f,g,h){if(!(d=d&&c.call(b,f,g,h)))return k});
return d};e.some=function(a,c,b){c||(c=e.identity);var d=false;if(a==null)return d;if(s&&a.some===s)return a.some(c,b);e.forEach(a,function(f,g,h){if(c.call(b,f,g,h)){d=true;return k}});return d};e.contains=function(a,c){var b=false;if(a==null)return b;if(j&&a.indexOf===j)return a.indexOf(c)!=-1;e.some(a,function(d){if(b=d===c)return true});return b};e.pluck=function(a,c){return e.map(a,function(b){return b[c]})};e.sortBy=function(a,c,b){return e.pluck(e.map(a,function(d,f,g){return{value:d,criteria:c.call(b,
d,f,g)}}).sort(function(d,f){var g=d.criteria,h=f.criteria;return g<h?-1:g>h?1:0}),"value")};e.sortedIndex=function(a,c,b){b||(b=e.identity);for(var d=0,f=a.length;d<f;){var g=d+f>>1;b(a[g])<b(c)?d=g+1:f=g}return d};e.toArray=function(a){if(!a)return[];if(a.toArray)return a.toArray();if(e.isArray(a))return a;if(e.isArguments(a))return l.call(a);return e.values(a)};e.last=function(a){var c=a.length;return c>0?a[c-1]:undefined};e.compact=function(a){return e.filter(a,function(c){return!!c})};e.flatten=
function(a){return e.reduce(a,function(c,b){if(e.isArray(b))return c.concat(e.flatten(b));c[c.length]=b;return c},[])};e.without=function(a){var c=l.call(arguments,1);return e.filter(a,function(b){return!e.contains(c,b)})};e.unique=function(a,c){return e.reduce(a,function(b,d,f){if(0==f||(c===true?e.last(b)!=d:!e.contains(b,d)))b[b.length]=d;return b},[])};e.intersect=function(a){var c=l.call(arguments,1);return e.filter(e.unique(a),function(b){return e.every(c,function(d){return e.indexOf(d,b)>=
0})})};e.indexOf=function(a,c,b){if(a==null)return-1;var d;if(b){b=e.sortedIndex(a,c);return a[b]===c?b:-1}if(j&&a.indexOf===j)return a.indexOf(c);b=0;for(d=a.length;b<d;b++)if(a[b]===c)return b;return-1};e.lastIndexOf=function(a,c){if(a==null)return-1;if(t&&a.lastIndexOf===t)return a.lastIndexOf(c);for(var b=a.length;b--;)if(a[b]===c)return b;return-1}})(K);

(function(c){var f=Object.create;c.extend=function(a,d){var b=function(){};b.prototype=d.prototype;var e=a.prototype;a.prototype=new b;a.$super=d;c.mix(a.prototype,e);return a};c.create=f||function(a,d){var b=function(e){e&&c.mix(this,e)};b.prototype=a;return new b(d)}})(K);

(function(c){c.bind=function(a,b){var e=Array.prototype.slice.call(arguments,2);return function(){b=b||(this==c.global?false:this);var d=e.concat(Array.prototype.slice.call(arguments));if(typeof a=="string"&&b[a])b[a].apply(b,d);else if(c.isFunction(a))return a.apply(b,d);else c.log("not function",a)}};c.methodize=function(a,b){if(b)return function(){return a.apply(null,[this[b]].concat([].slice.call(arguments)))};return function(){return a.apply(null,[this].concat([].slice.call(arguments)))}};c.delay=
function(a,b){var e=slice.call(arguments,2);return setTimeout(function(){return a.apply(a,e)},b)};c.defer=function(a){return c.delay.apply(c,[a,1].concat(slice.call(arguments,1)))};var f=function(){};c.Helper={methodize:function(a,b){var e=new f;for(var d in a)if(typeof a[d]=="function"&&!/^_/.test(d))e[d]=c.methodize(a[d],b);return e}}})(K);

(function(b){var e=Object.prototype,g=Array.prototype.slice,h=e.toString,f=e.hasOwnProperty;e=Array.isArray;b.keys=Object.keys||function(a){if(a!==Object(a))throw new TypeError("Invalid object");var c=[];for(var d in a)if(f.call(a,d))c[c.length]=d;return c};b.values=function(a){return b.map(a,b.identity)};b.methods=function(a){return b.filter(b.keys(a),function(c){return b.isFunction(a[c])}).sort()};b.mix=function(a){b.forEach(g.call(arguments,1),function(c){for(var d in c)if(c[d]!==void 0)a[d]=c[d]});
return a};b.clone=function(a){return b.isArray(a)?a.slice():b.mix({},a)};b.isEmpty=function(a){if(b.isArray(a)||b.isString(a))return a.length===0;for(var c in a)if(f.call(a,c))return false;return true};b.isElement=function(a){return!!(a&&a.nodeType==1)};b.isArray=e||function(a){return h.call(a)==="[object Array]"};b.isFunction=function(a){return!!(a&&a.constructor&&a.call&&a.apply)};b.isString=function(a){return!!(a===""||a&&a.charCodeAt&&a.substr)};b.isNumber=function(a){return!!(a===0||a&&a.toExponential&&
a.toFixed)};b.isNaN=function(a){return a!==a};b.isBoolean=function(a){return a===true||a===false};b.isDate=function(a){return!!(a&&a.getTimezoneOffset&&a.setUTCFullYear)};b.isRegExp=function(a){return!!(a&&a.test&&a.exec&&(a.ignoreCase||a.ignoreCase===false))};b.isNull=function(a){return a===null};b.isUndefined=function(a){return a===void 0};b.isArguments=function(a){return a&&b.isNumber(a.length)&&!a.concat&&!a.substr&&!a.apply&&!Object.prototype.propertyIsEnumerable.call(a,"length")};b.provide=
function(a,c){c=c||{};b[a]||(b[a]=c);return b[a]}})(K);

(function(c){c.trim=function(a){return a.replace(/^[\s\xa0\u3000]+|[\u3000\xa0\s]+$/g,"")};c.byteLen=function(a){return a.replace(/[^\x00-\xff]/g,"--").length};c.subByte=function(a,b,d){if(c.byteLen(a)<b)return a;d=d||"";b-=c.byteLen(d);return a.substr(0,b).replace(/([^\x00-\xff])/g,"$1 ").substr(0,b).replace(/[^\x00-\xff]$/,"").replace(/([^\x00-\xff]) /g,"$1")+d};c.encode4JS=function(a){return a.replace(/\\/g,"\\u005C").replace(/"/g,"\\u0022").replace(/'/g,"\\u0027").replace(/\//g,"\\u002F").replace(/\r/g,
"\\u000A").replace(/\n/g,"\\u000D").replace(/\t/g,"\\u0009")};c.encode4HTTP=function(a){return a.replace(/[\u0000-\u0020\u0080-\u00ff\s"'#\/\|\\%<>\[\]\{\}\^~;\?\:@=&]/,function(b){return encodeURIComponent(b)})};c.encode4Html=function(a){return a.replace(/&(?!\w+;|#\d+;|#x[\da-f]+;)/gi,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")};c.encode4HtmlValue=function(a){return c.encode4Html(a).replace(/"/g,"&quot;").replace(/'/g,
"&#039;")};c.stripTags=function(a){return a.replace(/<[^>]*>/gi,"")};c.formatDate=function(a,b){b=b||"yyyy-MM-dd";var d=a.getFullYear(),e={M:a.getMonth()+1,d:a.getDate(),h:a.getHours(),m:a.getMinutes(),s:a.getSeconds()};b=b.replace(/(y+)/ig,function(h,g){return(d+"").substr(4-Math.min(4,g.length))});for(var f in e)b=b.replace(RegExp("("+f+"+)","g"),function(h,g){return e[f]<10&&g.length>1?"0"+e[f]:e[f]});return b}})(K);

(function(b,c){function g(){b.windowFocused=true}function i(){b.windowFocused=false}b.Browser=function(){var d=c.navigator,h=d.userAgent.toLowerCase(),a={platform:d.platform};h.replace(/(msie|webkit|gecko|presto|opera|safari|firefox|chrome|maxthon)[ \/]([\d.]+)/ig,function(e,f,k){e=f.toLowerCase();a[e]=k});a.opera&&h.replace(/opera.*version\/([\d.]+)/,function(e,f){a.opera=f});if(a.msie){a.ie=a.msie;d=parseInt(a.msie,10);a["ie"+d]=true}if(a.safari&&a.chrome)a.safari=false;return a}();if(b.Browser.ie)try{c.document.execCommand("BackgroundImageCache",
false,true)}catch(j){}if(b.Browser.ie){c.document.attachEvent("onfocusin",g);c.document.attachEvent("onfocusout",i)}else{c.addEventListener("focus",g,false);c.addEventListener("blur",i,false)}})(K,this);
(function(b,c){var g;b.isSupportTouch=function(){if(g===c){b.log("detecting touch support");for(var i=["touchstart","touchmove","touchend"],j=true,d=document.createElement("div"),h=0,a=i.length;h<a;h++){var e="on"+i[h],f=e in d;if(!f){d.setAttribute(e,"return;");f=typeof d[e]=="function"}if(!f){j=false;break}}g=j}return g}})(K);

(function(e){var f=function(){this.__callbacks__={}};e.mix(f.prototype,{on:function(a,b,c){if(c)b=e.bind(b,c);var d=this.__callbacks__[a];if(d&&d.fired===true)b.apply(c,d.args);else{this.__callbacks__[a]=this.__callbacks__[a]||[];this.__callbacks__[a].push(b);return[a,b]}},un:function(a,b){if(e.isArray(a)){b=a[1];a=a[0]}if(a in this.__callbacks__){var c=this.__callbacks__[a];e.forEach(c,function(d,g){if(b==d||!b)c[g]=null})}},once:function(a,b,c){var d=this,g=this.on(a,function(){b.apply(c,arguments);
d.un(g)})},fire:function(a){if(a in this.__callbacks__){var b=this.__callbacks__[a],c=Array.prototype.slice.call(arguments,1);e.forEach(b,function(d){if(typeof d!="function")return null;return d.apply(null,c)})}},fireReady:function(a){var b=this.__callbacks__[a];b||(b=this.__callbacks__[a]=[]);if(!b.fired){var c=Array.prototype.slice.call(arguments,1);e.forEach(b,function(d){if(typeof d!="function")return null;return d.apply(null,c)});b.fired=true;b.args=c}}});e.Pubsub=f;e.mix(e,new f)})(K);

(function(b,g,v){function l(f,j,o){if(b.indexOf(j,f)>=0)throw Error("Module:"+f+" could't depends on itself!");this.id=f;this.dependancy=j;this.factory=o}var s={},w={};l.createRequire=function(f,j){function o(n,c){if(!c&&b.indexOf(f,n)==-1)throw Error(n+" counld't be required in "+j+", as you not declared to depend it ");var k=s[n];if(!k)return null;if(!k.exports){var i=k.factory;if(b.isFunction(i)){k.exports={};if(i=i(l.createRequire(k.dependancy,k.id),k.exports,k))k.exports=i}else if(i!==undefined)k.exports=
i}return k.exports}o.async=function(n,c,k){n=b.isString(n)?[n]:n;var i=b.unique(n),p=l.getDependancy(i);l.load(p);var t;if(b.Env.IS_DEV)t=setTimeout(function(){var r=b.Module.defined(),m=[];b.forEach(p,function(q){r[q]||m.push(q)});b.error(j+" require.async is waiting for: "+m.join())},1E4);l.wait(p,function(){clearTimeout(t);for(var r=[],m=0,q=n.length;m<q;m++)r.push(o(n[m],true));c.apply(k||v,r)})};return o};l.getDependancy=function(f){return g.getDependancy(f)};l.load=function(f){f=b.isString(f)?
[f]:f;b.forEach(f,function(j){g.loadModule(j)});g.autoLoad()};l.defined=function(){return s};l.waiting=function(){return b.keys(w)};l.check=function(f,j){f=b.trim(f);if(f.length==0||s[f])j&&j();else{w[f]=true;var o;if(b.Env.IS_DEV)o=setTimeout(function(){b.error("Module loading timeout: "+f)},1E4);b.on("Module:"+f+":Ready",function(){clearTimeout(o);j()})}};l.wait=function(f,j){f=[].concat(f);if(f.length>0){var o=f.shift();l.check(o,function(){l.wait(f,j)})}else j&&j()};v.define=b.define=function(f,
j,o){if(arguments.length<2)throw Error("module has invalid parameters");if(!b.isString(f))throw Error("module must have a ID");if(b.isFunction(j)){o=j;j=[]}else if(!b.isArray(j)){var n=j;o=function(){return n};j=[]}if(s[f])throw Error(f+" has defined");var c=b.unique(j);c=l.getDependancy(c);l.wait(c,function(){var k=new l(f,j,o);s[f]=k;try{delete w[f]}catch(i){}b.fire("Module:"+f+":Ready")});l.load(c)};v.Module=b.Module=l})(K,K.Resource,this);
(function(b,g){var v=g.resourceMap={},l=g.dependsMap={},s=g.resourceBasePath="../../../../../s.kaixin001.com.cn/",w=/\.js$/i,f={},j={},o=[],n=[],c;g.addResourceMap=function(a){b.mix(v,a);b.fire("Resource: Map Updated")};g.addResourceDepends=function(a){b.mix(l,a)};g.setBasePath=function(a){s=a};g.getDependancy=function(a,d){var e=[];a=b.isString(a)?[a]:a;d=d||[];b.forEach(a,function(h){h=h.replace(w,"");d=d.concat(e);b.indexOf(d,h)==-1&&e.unshift(h);if(h=l[h+".js"]){h=g.getDependancy(h,d);h.length&&e.unshift.apply(e,
h)}});return e};var k=/^\/+|\/+$/ig,i={},p={},t={},r,m=false;g.passiveLoad=function(a){a=b.isArray(a)?a:[a];b.forEach(a,function(d){i[d]=1;delete p[d]})};g.enableAutoLoad=function(){r="http://"+b.Env.KX_HOST+"/interface/resourcemap.php";m=true;g.autoLoad()};g.disableAutoLoad=function(){m=false};g.getCanonicalId=function(a){a.indexOf("core/")==0||a.indexOf("apps/")==0||(a=a.indexOf("/")==-1?"core/"+a:"apps/"+a);return a};g.lookupResourceMap=function(a){w.test(a)||(a+=".js");return v[a]};g.loadModule=
function(a){a=a.replace(k,"");a=g.getCanonicalId(a);if(!i[a]){var d=g.lookupResourceMap(a);if(d){i[a]=1;g.loadJS(s+d)}else{p[a]=1;g.autoLoad()}}};g.autoLoad=function(){if(m){var a=[];b.forEach(p,function(x,y){if(!t[y]){t[y]=1;a.push(y)}});var d=a.length,e=0;for(e=0;e<d/7;e++){var h=a.slice(e*7,(e+1)*7);g.loadJS(r+"@modules="+h.join(","))}}};g.onMapUpdate=function(){var a=[];b.forEach(p,function(d,e){var h=g.lookupResourceMap(e);if(h){i[e]=1;a.push(e);g.loadJS(s+h)}});b.forEach(a,function(d){delete p[d]});
g.autoLoad()};b.on("Resource: Map Updated",g.onMapUpdate);g.canonicalURI=function(a){if(/^\/\/\/?/.test(a))a=location.protocol+a;return a};var q=function(){for(var a=document.getElementsByTagName("link"),d=a.length,e;d;){e=a[--d];if((e.rel=="stylesheet"||e.type=="text/css")&&e.href)f[g.canonicalURI(e.href)]=true}a=document.getElementsByTagName("script");for(d=a.length;d;){e=a[--d];if((!e.type||e.type=="text/javascript")&&e.src)f[g.canonicalURI(e.src)]=true}q=function(){}},u=function(a){var d,e;delete j[a];
f[a]=true;for(e=0;e<o.length;e++){d=o[e];delete d.resources[a];if(b.isEmpty(d.resources)){d.callback&&d.callback();o.splice(e--,1)}}},z=function(){for(var a=document.styleSheets,d=a.length;d--;){var e=a[d],h=false;if(b.Browser.firefox)try{if(e.cssRules)h=true}catch(x){if(x.name==="SecurityError"||x.name==="NS_ERROR_DOM_SECURITY_ERR")h=true}else h=true;if(h){e=e.ownerNode||e.owningElement;h=n.length;if(e)for(;h--;)if(e==n[h]){u(n[h]["data-href"]);n.splice(h,1)}}}if(!n.length){clearInterval(c);c=null}},
B=function(a){var d=document.createElement("script"),e=function(){d.onload=d.onerror=d.onreadystatechange=null;u(a)};b.mix(d,{type:"text/javascript",src:a});d.onload=d.onerror=e;d.onreadystatechange=function(){var h=this.readyState;if(h=="complete"||h=="loaded")e()};document.getElementsByTagName("head")[0].appendChild(d)},C=function(a){var d=document.createElement("link");b.mix(d,{type:"text/css",rel:"stylesheet",href:a,"data-href":a});document.getElementsByTagName("head")[0].appendChild(d);if(d.attachEvent)d.onload=
function(){u(a)};else{n.push(d);c||(c=setInterval(z,20))}},A=function(a,d){var e={},h;q();a=b.isArray(a)?a:[a];for(var x=0,y=a.length;x<y;x++){h=g.canonicalURI(a[x]);e[h]=true;if(f[h])setTimeout(b.bind(u,null,h),0);else if(!j[h]){j[h]=true;h.indexOf(".css")>-1?C(h):B(h)}}d&&o.push({resources:e,callback:d})};g.loadJS=function(a,d){A(a,d)};g.loadCSS=function(a,d){A(a,d)}})(K,K.Resource);
(function(b,g){function v(c,k,i){if(j[c])throw Error("App:"+c+" has defined");j[c]=this;this.id=c;this.requiredModList=["jQuery"].concat(k);this.execBeforeDomready=i}function l(c,k){var i;if(!c.container)c.container=document.body;i=k(c.container);if(!i.length||i.length>1)i=k(document.body);c.container=i;c.getContainer=function(){return i};return i}function s(c,k,i){b.map(c.events,function(p,t){var r=t.match(o),m=r[1];r=r[2];var q=k.proxy(c[p],c);r?i.delegate(r,m,k.proxy(c[p],c)):i.bind(m,q)})}function w(c){return b.detect(c,
function(k){return b.isArray(k)})||[]}var f="require getContainer".split(/\s+/ig),j={};b.mix(v.prototype,{define:function(c){var k=b.unique(this.requiredModList),i=g.getDependancy(k),p=this,t=function(){b.fire("App:"+p.id+":Ready",p,c)};g.load(i);var r;if(b.Env.IS_DEV)r=setTimeout(function(){var m=b.Module.defined(),q=[];b.forEach(i,function(u){m[u]||q.push(u)});b.error('App "'+p.id+'" is waiting for: '+q.join())},1E4);g.wait(i,function(){clearTimeout(r);var m=g.createRequire(k,p.id);if(b.isFunction(c))c=
c.call({require:g.createRequire(k,p.id)},m);if(p.definition=c){var q,u,z;q=0;for(u=f.length;q<u;q++){z=f[q];if(c[z])throw Error(z+" is a reserve method or property");}c.require=m;m=c.require("jQuery");p.__jQuery__=m;if(!(c.container&&m(c.container).length==0)){q=l(c,m);c.events&&s(c,m,q);if(b.isFunction(c.main))if(p.execBeforeDomready){c.main();t()}else b.ready(function(){c.main();t()});else t()}}})}});var o=/^([\w\.]+)(?:\s+(.*))?$/,n=0;b.App=function(){var c;if((c=arguments[0])&&b.isString(c)){if(b.last(c.split(/\//ig)).charAt(0)!=
"A")throw Error(c+" is a invalid name for a App");}else c="__APP__"+n++;c=c;var k=w(arguments),i;i=b.last(arguments);i=b.isBoolean(i)?i:false;return new v(c,k,i)};b.App.get=function(c){return j[c]||null};b.App.getAll=function(){return j}})(K,K.Module);

(function(d){var f=d.mix,i=d.indexOf,g=d.CustEvent=function(a,c,b){this.target=a;this.type=c;f(this,b||{})};f(g.prototype,{target:null,currentTarget:null,type:null,returnValue:undefined,preventDefault:function(){this.returnValue=false}});d.CustEventTargetH={on:function(a,c,b){a=a.__custListeners&&a.__custListeners[c]||d.error("unknown event type",TypeError);if(i(a,b)>-1)return false;a.push(b);return true},un:function(a,c,b){a=a.__custListeners&&a.__custListeners[c]||d.error("unknown event type",TypeError);
if(b){b=i(a,b);if(b<0)return false;a.splice(b,1)}else a.length=0;return true},fire:function(a,c,b){if(c instanceof g){b=f(c,b);c=c.type}else b=new g(a,c,b);var e=a.__custListeners&&a.__custListeners[c]||d.error("unknown event type",TypeError);if(c!="*")e=e.concat(a.__custListeners["*"]||[]);b.returnValue=undefined;b.currentTarget=a;if((a=b.currentTarget)&&a["on"+b.type])var j=a["on"+b.type].call(a,b);for(c=0;c<e.length;c++)e[c].call(a,b);return b.returnValue!==false||j===false&&b.returnValue===undefined},
createEvents:function(a,c){c=c||[];if(typeof c=="string")c=c.split(",");var b=a.__custListeners;if(!b)b=a.__custListeners={};for(var e=0;e<c.length;e++)b[c[e]]=b[c[e]]||[];b["*"]=b["*"]||[];return a}};var h=d.CustEventTarget=function(){this.__custListeners={}},k=d.Helper.methodize(d.CustEventTargetH,null,{on:"operator",un:"operator"});f(h.prototype,k);d.CustEvent.createEvents=h.createEvents=function(a,c){d.CustEventTargetH.createEvents(a,c);return f(a,h.prototype)}})(K);

(function(b){b.Env={IS_LITE:../../../../kx00[145]/.com/.test(location.host)||/kaixin00[128]\.cc/.test(location.host),KX_HOST:"www.kaixin001.com",IMG_HOST:"img1.kaixin001.com.cn",IS_DEV:!/(kx|kaixin)001\.com/.test(location.host)};b.mix(b.Env,{getDomain:function(){var c;c=b.Env.THIS_HOST;var a=(window.location+"").match(/:\/\/[^\/]+\.(kaixin|kx)(00[^\/])(\.com|\.cc)/i);if(a&&a[1]&&a[2]&&a[3])c="."+a[1]+a[2]+a[3];return c},getDomainND:function(){return b.Env.getDomain().substr(1)}})})(K);

(function(b){b.identity=function(g){return g};var e=0;b.uniqueId=function(g){var f=e++;return g?g+f:f}})(K);
(function(b){var e=false,g=false;b.ready=function(a){e?a():b.on("Onload:DomContentLoaded",a)};var f=function(){if(!e){e=true;b.fire("Onload:DomContentLoaded")}},h;if(document.addEventListener)h=function(){document.removeEventListener("DOMContentLoaded",h,false);f()};else if(document.attachEvent)h=function(){if(document.readyState==="complete"){document.detachEvent("onreadystatechange",h);f()}};var j=function(){if(!e){try{document.documentElement.doScroll("left")}catch(a){setTimeout(j,1);return}document.detachEvent("onreadystatechange",
h);f()}};(function(){var a=b.global,c=a.document,d=function(){if(!e){e=true;f()}if(!g){g=true;b.fire("Onload:Loaded")}};if(c.readyState=="complete")setTimeout(f,0);else if(c.addEventListener){c.addEventListener("DOMContentLoaded",h,false);a.addEventListener("load",d,false)}else if(c.attachEvent){c.attachEvent("onreadystatechange",h);a.attachEvent("onload",d);d=false;try{d=!a.frameElement}catch(i){}c.documentElement.doScroll&&d&&j()}})()})(K);
(function(b){b.onbeforeunload=function(e){if(e)if(typeof window.onbeforeunload=="function"){var g=window.onbeforeunload;window.onbeforeunload=function(){var f=e.apply(null,arguments),h=g.apply(null,arguments);return h?h:f}}else window.onbeforeunload=e}})(K);(function(b){b.logs=function(e,g){var f="s2";if(b.isArray(e)||e.indexOf(",")>-1){f="ss2";if(b.isArray(e))e=e.join(",")}window.jQuery.post("../../../../interface/s.php",{type:f,key:e},function(){g&&g()})}})(K);
(function(b){b.Perf=b.Performance={timing:{},marks:{}};var e=window.performance||window.msPerformance||window.webkitPerformance||window.mozPerformance;if(e&&e.timing)b.Performance.timing=e.timing;else b.ready(function(){b.Performance.timing={responseStart:b.global.g_st_time,domContentLoadedEventStart:(new Date).getTime()}});b.Perf.markTime=function(g,f,h){if(h||!b.Perf.marks[g])b.Perf.marks[g]=f||new Date*1};b.Perf.getMarks=function(){var g=[];for(var f in b.Perf.marks)b.Perf.marks.hasOwnProperty(f)&&
g.push(f+"="+(b.Perf.marks[f]-b.global.g_st_time));return g.join("&")};b.ready(function(){b.Perf.markTime("wpo_domready")})})(K);
(function(b){var e=function(a,c){for(c=c.toUpperCase();a&&a.nodeName!=c;)a=a.parentNode;return a},g=function(a){a:if("hasAttribute"in a)a=a.getAttribute("data-app");else{if("getAttributeNode"in a)if(a=a.getAttributeNode("data-app")){a=a.value;break a}a=void 0}var c;if(c=a){if(c=a.length){c=a;if(!("App"in b)||!b.App.get(c)){b.log(c,"not ready");c=false}else c=true;c=!c}c=c}if(c)return a;return false},f=function(a,c,d){var i=g(a),l;if(i){b.once("App:"+i+":Ready",function(k){k.__jQuery__(d||a)[c]()});
return false}else if(c=="click")if((i=a.getAttribute("data-ajax"))&&i.length){l=a.getAttribute("data-ajax-url")||a.href;switch(i){case "dialog-post":case "dialog":b.Module.createRequire().async("core/panel/AsyncDialog",function(k){k.load(l,a)});break;case "request-post":case "request":b.Module.createRequire().async("core/async/Request",function(k){k.load(l,a)});break;default:return}return false}},h=function(a){a=e(a,"FORM")||a;return f(a,"submit")},j=function(){var a=document.createElement("div"),
c="onsubmit"in a;if(!c){a.setAttribute("onsubmit","return;");c=typeof a.onsubmit==="function"}return c}();(function(){var a=b.global.document.documentElement,c=null;a.onclick=function(d){d=d||window.event;c=d.target||d.srcElement;if(!j){d=c.type;if(d=="submit"||d=="image")return h(c)}d=c;var i=e(d,"A")||d;return f(i,"click",d)};if(!j)a.onkeypress=function(d){d=d||window.event;c=d.target||d.srcElement;var i=c.type;if((i=="text"||i=="password")&&d.keyCode==13)return h(c)};if(j)a.onsubmit=function(d){d=
d||window.event;return h(d.target||d.srcElement)}})()})(K);
