<?php  if(!defined('IN_UCHOME')) { exit('Access Denied'); } class dbstuff { var $querynum = 0; var $link; var $KGn1g4iOB; var $charset_wap; function connect($dbhost, $dbuser, $dbpw, $dbname = '', $pconnect = 0, $halt = TRUE) { if($pconnect) { if(!$this->link = @mysql_pconnect($dbhost, $dbuser, $dbpw)) { $halt && $this->halt('Can not connect to MySQL server'); } } else { if(!$this->link = @mysql_connect($dbhost, $dbuser, $dbpw, 1)) { $halt && $this->halt('Can not connect to MySQL server'); } } if($this->version() > '4.1') { if($this->KGn1g4iOB) { @mysql_query("SET character_set_connection=$this->KGn1g4iOB, character_set_results=$this->KGn1g4iOB, character_set_client=binary", $this->link); } if($this->version() > '5.0.1') { @mysql_query("SET \163\x71l_\155od\x65=''", $this->link); } } if($dbname) { @mysql_select_db($dbname, $this->link); } } function select_db($dbname) { return mysql_select_db($dbname, $this->link); } function fetch_array($query, $result_type = MYSQL_ASSOC) { if($this->KGn1g4iOB == $this->charset_wap) { return mysql_fetch_array($query, $result_type); } else { $result = mysql_fetch_array($query, $result_type); $result = fYZ4g87Nj($result); return $result; } } function query($sql, $type = '') { if($this->KGn1g4iOB != $this->charset_wap) { $sql = fYZ4g87Nj($sql,0); } if(D_BUG) { global $_SGLOBAL; $sqlstarttime = $sqlendttime = 0; $mtime = explode(' ', microtime()); $sqlstarttime = number_format(($mtime[1] + $mtime[0] - $_SGLOBAL['supe_starttime']), 6) * 1000; } $func = $type == 'UNBUFFERED' && @function_exists('mysql_unbuffered_query') ? 'mysql_unbuffered_query' : 'mysql_query'; if(!($query = $func($sql, $this->link)) && $type != 'SILENT') { $this->halt('MySQL Query Error', $sql); } if(D_BUG) { $mtime = explode(' ', microtime()); $sqlendttime = number_format(($mtime[1] + $mtime[0] - $_SGLOBAL['supe_starttime']), 6) * 1000; $sqltime = round(($sqlendttime - $sqlstarttime), 3);
$explain = array(); $info = mysql_info(); if($query && preg_match("/^(select )/i", $sql)) { $explain = mysql_fetch_assoc(mysql_query('EXPLAIN '.$sql, $this->link)); } $_SGLOBAL['debug_query'][] = array('sql'=>$sql, 'time'=>$sqltime, 'info'=>$info, 'explain'=>$explain); } $this->querynum++; return $query; } function affected_rows() { return mysql_affected_rows($this->link); } function error() { return (($this->link) ? mysql_error($this->link) : mysql_error()); } function errno() { return intval(($this->link) ? mysql_errno($this->link) : mysql_errno()); } function result($query, $row) { $query = @mysql_result($query, $row); return $query; } function num_rows($query) { $query = mysql_num_rows($query); return $query; } function num_fields($query) { return mysql_num_fields($query); } function free_result($query) { return mysql_free_result($query); } function insert_id() { return ($id = mysql_insert_id($this->link)) >= 0 ? $id : $this->result($this->query("\x53E\x4c\x45\x43T last_insert_id()"), 0); } function fetch_row($query) { $query = mysql_fetch_row($query); return $query; } function fetch_fields($query) { return mysql_fetch_field($query); } function version() { return mysql_get_server_info($this->link); } function close() { return mysql_close($this->link); } function halt($message = '', $sql = '') { $dberror = $this->error(); $dberrno = $this->errno(); $help_link = "http://faq.comsenz.\x63\157m/?type=m\x79\x73\161l&dberrno=".rawurlencode($dberrno)."&dberror=".rawurlencode($dberror); echo "<div style=\"position:absolute;font-size:11px;font-family:\166\145\162\x64a\156a,\x61\x72\151\141\x6c;background:#EBEBEB;padding:0.5em;\">
				<b>MySQL Er\162o\x72</b><br>
				<b>\115\x65\163\163a\x67\x65</b>: $message<br>
				<b>SQ\114</b>: $sql<br>
				<b>E\x72\162\157r</b>: $dberror<br>
				<b>E\x72\162\x6eo.</b>: $dberrno<br>
				<a href=\"$help_link\" target=\"_blank\">C\x6c\151\143\153 here to seek help.</a>
				</div>"; exit(); } } ; ?>
