<?php   if(!defined('IN_UCHOME') || !defined('IN_WAP')) { exit('Access Denied'); } $_SGLOBAL['i'] = 0; $_SGLOBAL['block_search'] = $_SGLOBAL['block_replace'] = array(); function parse_template($tpl) { global $_SGLOBAL, $_SC, $_SCONFIG;  
$_SGLOBAL['sub_tpls'] = array($tpl); $tplfile = S_ROOT.'./'.$tpl.'.htm'; $objfile = S_ROOT.'./data/tpl_cache/'.str_replace('/','_',$tpl).'.php';  
if(!file_exists($tplfile)) { $tplfile = str_replace('/'.$_SCONFIG['template'].'/', '/default/', $tplfile); } $template = sreadfile($tplfile); if(empty($template)) { exit("\124e\x6d\160\x6c\x61t\x65 \146\x69l\145 : $tplfile N\x6f\164 found \157r have \156o \x61c\x63es\163!"); }  
$template = preg_replace("/\<\!\-\-\{template\s+([a-z0-9_\/]+)\}\-\-\>/ie", "readtemplate('\\1')", $template);  
$template = preg_replace("/\<\!\-\-\{template\s+([a-z0-9_\/]+)\}\-\-\>/ie", "readtemplate('\\1')", $template);  
$template = preg_replace("/\<\!\-\-\{block\/(.+?)\}\-\-\>/ie", "blocktags('\\1')", $template);  
$template = preg_replace("/\<\!\-\-\{\141d\/(.+?)\}\-\-\>/ie", "adtags('\\1')", $template);  
$template = preg_replace("/\<\!\-\-\{\x64a\x74\x65\((.+?)\)\}\-\-\>/ie", "datetags('\\1')", $template);  
$template = preg_replace("/\<\!\-\-\{avatar\((.+?)\)\}\-\-\>/ie", "avatartags('\\1')", $template);  
$template = preg_replace("/\<\!\-\-\{\x65\166\141l\s+(.+?)\s*\}\-\-\>/ies", "evaltags('\\1')", $template);  
 
$var_regexp = "((\\\$[a-zA-Z_\x7f-\xff][a-zA-\132\060-9_\x7f-\xff]*)(\[[a-zA-\132\x30-9_\-\.\"\'\[\]\$\x7f-\xff]+\])*)"; $template = preg_replace("/\<\!\-\-\{(.+?)\}\-\-\>/s", "{\\1}", $template); $template = preg_replace("/([\n\r]+)\t+/s", "\\1", $template); $template = preg_replace("/(\\\$[a-zA-\x5a\060-9_\[\]\'\"\$\x7f-\xff]+)\.([a-zA-Z_\x7f-\xff][a-zA-\x5a\x30-9_\x7f-\xff]*)/s", "\\1['\\2']", $template); $template = preg_replace("/\{(\\\$[a-zA-Z\x30-9_\[\]\'\"\$\.\x7f-\xff]+)\}/s", "<?=\\1?>", $template); $template = preg_replace("/$var_regexp/es", "addquote('<?=\\1?>')", $template); $template = preg_replace("/\<\?\=\<\?\=$var_regexp\?\>\?\>/es", "addquote('<?=\\1?>')", $template);  
$template = preg_replace("/\{\145\154s\145\x69f\s+(.+?)\}/ies", "stripvtags('<?\160\150\160 } e\x6c\x73\x65\151\x66(\\1) { ?>','')", $template); $template = preg_replace("/\{\x65l\163e\}/\x69\163", "<?php } \x65\154\163e { ?>", $template);  
for($i = 0; $i < 6; $i++) { $template = preg_replace("/\{loop\s+(\S+)\s+(\S+)\}(.+?)\{\/loop\}/ies", "stripvtags('<?\x70\150\x70 \151\x66(i\163_\141\x72\162\141\x79(\\1)) { \x66\157\x72\x65a\x63\150(\\1 \141\x73 \\2) { ?>','\\3<?p\x68\160 } } ?>')", $template); $template = preg_replace("/\{loop\s+(\S+)\s+(\S+)\s+(\S+)\}(.+?)\{\/loop\}/ies", "stripvtags('<?\x70\x68\x70 \151f(\151\163_a\162\162\x61y(\\1)) { \x66\x6fre\x61\143\150(\\1 \141\163 \\2 => \\3) { ?>','\\4<?\x70\150\x70 } } ?>')", $template); $template = preg_replace("/\{\151\146\s+(.+?)\}(.+?)\{\/\x69f\}/ies", "stripvtags('<?\x70\x68\x70 \x69f(\\1) { ?>','\\2<?ph\160 } ?>')", $template); }  
$template = preg_replace("/\{([a-zA-Z_\x7f-\xff][a-zA-\x5a\060-9_\x7f-\xff]*)\}/s", "<?=\\1?>", $template);  
if(!empty($_SGLOBAL['block_search'])) { $template = str_replace($_SGLOBAL['block_search'], $_SGLOBAL['block_replace'], $template); }  
$template = preg_replace("/ \?\>[\n\r]*\<\? /s", " ", $template);  
$template = "<?\160hp i\x66(!\144\145\146\x69ne\144('IN_UCHOME')) \x65xi\164('Access Denied');?><?p\150\160 subtplcheck('".implode('|', $_SGLOBAL['sub_tpls'])."', '$_SGLOBAL[timestamp]', '$tpl');?>$template<?ph\x70 ob_out();?>";  
if(!swritefile($objfile, $template)) { exit("File: $objfile \143a\156 n\157\164 be write!"); } } function addquote($var) { return str_replace("\\\"", "\"", preg_replace("/\[([a-zA-\132\x30-9_\-\.\x7f-\xff]+)\]/s", "['\\1']", $var)); } function striptagquotes($expr) { $expr = preg_replace("/\<\?\=(\\\$.+?)\?\>/s", "\\1", $expr); $expr = str_replace("\\\"", "\"", preg_replace("/\[\'([a-zA-\x5a0-9_\-\.\x7f-\xff]+)\'\]/s", "[\\1]", $expr)); return $expr; } function evaltags($php) { global $_SGLOBAL; $_SGLOBAL['i']++; $search = "<!--EVAL_TAG_{$_SGLOBAL['i']}-->"; $_SGLOBAL['block_search'][$_SGLOBAL['i']] = $search; $_SGLOBAL['block_replace'][$_SGLOBAL['i']] = "<?\x70\150\160 ".stripvtags($php)." ?>"; return $search; } function blocktags($parameter) { global $_SGLOBAL; $_SGLOBAL['i']++; $search = "<!--BLOCK_TAG_{$_SGLOBAL['i']}-->"; $_SGLOBAL['block_search'][$_SGLOBAL['i']] = $search; $_SGLOBAL['block_replace'][$_SGLOBAL['i']] = "<?p\x68\160 block(\"$parameter\"); ?>"; return $search; } function adtags($pagetype) { global $_SGLOBAL; $_SGLOBAL['i']++; $search = "<!--AD_TAG_{$_SGLOBAL['i']}-->"; $_SGLOBAL['block_search'][$_SGLOBAL['i']] = $search; $_SGLOBAL['block_replace'][$_SGLOBAL['i']] = "<?\160\150p adshow('$pagetype'); ?>"; return $search; } function datetags($parameter) { global $_SGLOBAL; $_SGLOBAL['i']++; $search = "<!--DATE_TAG_{$_SGLOBAL['i']}-->"; $_SGLOBAL['block_search'][$_SGLOBAL['i']] = $search; $_SGLOBAL['block_replace'][$_SGLOBAL['i']] = "<?\160\150\x70 e\143\x68o sgmdate($parameter); ?>"; return $search; } function avatartags($parameter) { global $_SGLOBAL; $_SGLOBAL['i']++; $search = "<!--AVATAR_TAG_{$_SGLOBAL['i']}-->"; $_SGLOBAL['block_search'][$_SGLOBAL['i']] = $search; $_SGLOBAL['block_replace'][$_SGLOBAL['i']] = "<?\x70\x68p echo avatar($parameter); ?>"; return $search; } function stripvtags($expr, $statement='') { $expr = str_replace("\\\"", "\"", preg_replace("/\<\?\=(\\\$.+?)\?\>/s", "\\1", $expr)); $statement = str_replace("\\\"", "\"", $statement); return $expr.$statement; } function readtemplate($name) { global $_SGLOBAL, $_SCONFIG; $tpl = strexists($name,'/')?$name:"wap/tpl/$_SCONFIG[template]/$name"; $tplfile = S_ROOT.'./'.$tpl.'.htm'; $_SGLOBAL['sub_tpls'][] = $tpl; if(!file_exists($tplfile)) { $tplfile = str_replace('/'.$_SCONFIG['template'].'/', '/default/', $tplfile); } $content = sreadfile($tplfile); return $content; } ; ?>
