<?php   if(!defined('IN_UCHOME') || !defined('IN_WAP')) { exit('Access Denied'); }  
if($space['namestatus']) { include_once(S_ROOT.'./source/function_cp.php'); if(!ckrealname('viewspace', 1)) { $_SGLOBAL['realname_privacy'] = 1; include template('space_privacy'); exit(); } }  
$_SGLOBAL['space_theme'] = $space['theme']; $_SGLOBAL['space_css'] = $space['css'];  
$space['isfriend'] = $space['self']; if($space['friends'] && in_array($_SGLOBAL['supe_uid'], $space['friends'])) { $space['isfriend'] = 1; 
}  
 
$space['sex_org'] = $space['sex']; $space['sex'] = $space['sex']=='1'? lang('man'):($space['sex']=='2'? lang('woman'):''); $space['birth'] = ($space['birthyear']?"$space[birthyear]".lang('year'):'').($space['birthmonth']?"$space[birthmonth]".lang('month'):'').($space['birthday']?"$space[birthday]".lang('day'):''); $space['marry'] = $space['marry']=='1'?'<a href="cp.php?ac=friend&op=search&marry=1&searchmode=1">'.lang('unmarried').'</a>':($space['marry']=='2'?'<a href="cp.php?ac=friend&op=search&marry=2&searchmode=1">'.lang('married').'</a>':''); $space['birthcity'] = trim(($space['birthprovince']?"<a href=\"cp.ph\x70?ac=friend&op=search&birthprovince=".rawurlencode($space['birthprovince'])."&searchmode=1\">$space[birthprovince]</a>":'').($space['birthcity']?" <a href=\"cp.\x70\150\x70?ac=friend&op=search&birthcity=".rawurlencode($space['birthcity'])."&searchmode=1\">$space[birthcity]</a>":'')); $space['residecity'] = trim(($space['resideprovince']?"<a href=\"cp.\160\150p?ac=friend&op=search&resideprovince=".rawurlencode($space['resideprovince'])."&searchmode=1\">$space[resideprovince]</a>":'').($space['residecity']?" <a href=\"cp.\x70hp?ac=friend&op=search&residecity=".rawurlencode($space['residecity'])."&searchmode=1\">$space[residecity]</a>":'')); $space['qq'] = empty($space['qq'])?'':"<a target=\"_blank\" href=\"http://wpa.qq.\143\x6f\155/msgrd?V=1&Uin=$space[qq]&S\x69\164\145=$space[username]&Me\156u=yes\">$space[qq]</a>";  
$query = $_SGLOBAL['db']->query("S\x45\114\105\x43\124 * \106\122O\115 ".tname('spaceinfo')." WHERE uid='$space[uid]' AND type IN ('base', 'contact')"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { $v_friend = ckfriend($value['uid'], $value['friend']); if(!$v_friend) $space[$value['subtype']] = ''; } @include_once(S_ROOT.'./data/data_usergroup.php');  
$space['star'] = getstar($space['experience']);  
$space['domainurl'] = space_domain($space);  
$feedlist = array(); if(ckprivacy('feed')) { $query = $_SGLOBAL['db']->query("SE\x4cE\x43\x54 * \x46\x52\x4f\x4d ".tname('feed')." WHERE uid='$space[uid]' ORDER BY dateline DESC LIMIT 0,20"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { if(ckfriend($value['uid'], $value['friend'], $value['target_ids'])) { realname_set($value['uid'], $value['username']); $feedlist[] = $value; } } $feednum = count($feedlist); }  
$oluids = array(); $friendlist = array(); if(ckprivacy('friend')) { $query = $_SGLOBAL['db']->query("\123E\x4c\105\x43\124 * \106R\x4f\x4d ".tname('friend')." WHERE uid='$space[uid]' AND \x73\164\x61\x74u\163='1' ORDER BY num DESC, dateline DESC LIMIT 0,16"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['fuid'], $value['fusername']); $oluids[$value['fuid']] = $value['fuid']; $friendlist[] = $value; } if($friendlist && empty($space['friendnum'])) {  
include_once(S_ROOT.'./source/function_cp.php'); friend_cache($space['uid']); } }  
$visitorlist = array(); $query = $_SGLOBAL['db']->query("\123EL\x45C\124 * \106\x52\117M ".tname('visitor')." WHERE uid='$space[uid]' ORDER BY dateline DESC LIMIT 0,16"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { if($value['vusername']) { realname_set($value['vuid'], $value['vusername']); } $value['isfriend'] = 0; if($space['friends'] && in_array($value['vuid'], $space['friends'])) { $value['isfriend'] = 1; } $oluids[$value['vuid']] = $value['vuid']; $visitorlist[$value['vuid']] = $value; }  
$viewuids = $_SCOOKIE['viewuids']?explode('_', $_SCOOKIE['viewuids']):array(); if($_SGLOBAL['supe_uid'] && !$space['self'] && !in_array($space['uid'], $viewuids)) { $_SGLOBAL['db']->query("UPDATE ".tname('space')." SET viewnum=viewnum+1 WHERE uid='$space[uid]'");  
$viewuids[$space['uid']] = $space['uid']; ssetcookie('viewuids', implode('_', $viewuids)); }  
$bloglist = array(); if($space['blognum'] && ckprivacy('blog')) { $query = $_SGLOBAL['db']->query("\123\x45\114\x45C\124 b.uid, b.blogid, b.subject, b.dateline, b.pic, b.picflag, b.viewnum, b.replynum, b.friend, b.password, bf.message, bf.target_ids
		\106\x52\x4fM ".tname('blog')." b
		LEFT JOIN ".tname('blogfield')." bf \117\x4e bf.blogid=b.blogid
		WHERE b.uid='$space[uid]'
		ORDER BY b.dateline DESC LIMIT 0,5"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { if(ckfriend($value['uid'], $value['friend'], $value['target_ids'])) { if($value['pic']) $value['pic'] = pic_cover_get($value['pic'], $value['picflag']); $value['message'] = $value['friend']==4?'':getstr($value['message'], 150, 0, 0, 0, 0, -1); $bloglist[] = $value; } } $blognum = count($bloglist); }  
$albumlist = array(); if($space['albumnum'] && ckprivacy('album')) { $query = $_SGLOBAL['db']->query("S\105L\x45\103T * F\x52OM ".tname('album')." WHERE uid='$space[uid]' ORDER BY updatetime DESC LIMIT 0,2"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { if(ckfriend($value['uid'], $value['friend'], $value['target_ids'])) { $value['pic'] = pic_cover_get($value['pic'], $value['picflag']); $albumlist[] = $value; } } }  
$walllist = array(); if(ckprivacy('wall')) { $query = $_SGLOBAL['db']->query("\123\105\x4cE\x43\x54 * FR\x4f\115 ".tname('comment')." WHERE id='$space[uid]' AND idtype='uid' ORDER BY dateline DESC LIMIT 0,5"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['authorid'], $value['author']); $value['message'] = strlen($value['message'])>500?getstr($value['message'], 500, 0, 0, 0, 0, -1).' ...':$value['message']; $walllist[] = $value; } }  
$query = $_SGLOBAL['db']->query('SELECT * FROM '.tname('session')." WHERE uid = '$space[uid]'"); $value = $_SGLOBAL['db']->fetch_array($query); $isonline = (empty($value) || $value['magichidden']) ? 0 : sgmdate('H:i:s', $value['lastactivity'], 1);  
$theme = empty($_GET['theme'])?'':preg_replace("/[^0-9a-z]/i", '', $_GET['theme']); if($theme == 'uchomedefault') { $_SGLOBAL['space_theme'] = $_SGLOBAL['space_css'] = ''; } elseif($theme) { $cssfile = S_ROOT.'./theme/'.$theme.'/style.css'; if(file_exists($cssfile)) { $_SGLOBAL['space_theme'] = $theme; $_SGLOBAL['space_css'] = ''; } } else { if(!$space['self'] && $_SGLOBAL['member']['nocss']) { $_SGLOBAL['space_theme'] = $_SGLOBAL['space_css'] = ''; } }  
if(!$space['self'] && $_SGLOBAL['supe_uid']) { $query = $_SGLOBAL['db']->query("\x53\105\x4c\105C\124 dateline \x46\x52O\x4d ".tname('visitor')." WHERE uid='$space[uid]' AND vuid='$_SGLOBAL[supe_uid]'"); $visitor = $_SGLOBAL['db']->fetch_array($query); $is_anonymous = empty($_SCOOKIE['anonymous_visit_'.$_SGLOBAL['supe_uid'].'_'.$space['uid']]) ? 0 : 1; if(empty($visitor['dateline'])) { $setarr = array( 'uid' => $space['uid'], 'vuid' => $_SGLOBAL['supe_uid'], 'vusername' => $is_anonymous ? '' : $_SGLOBAL['supe_username'], 'dateline' => $_SGLOBAL['timestamp'] ); inserttable('visitor', $setarr, 0, true); show_credit(); 
} else { if($_SGLOBAL['timestamp'] - $visitor['dateline'] >= 300) { updatetable('visitor', array('dateline'=>$_SGLOBAL['timestamp'], 'vusername'=>$is_anonymous ? '' : $_SGLOBAL['supe_username']), array('uid'=>$space['uid'], 'vuid'=>$_SGLOBAL['supe_uid'])); } if($_SGLOBAL['timestamp'] - $visitor['dateline'] >= 3600) { show_credit(); 
} }  
getreward('visit', 1, 0, $space['uid']); }  
$space['magiccredit'] = 0; if($_SGLOBAL['magic']['gift'] && $_SGLOBAL['supe_uid']) { $query = $_SGLOBAL['db']->query('SELECT * FROM '.tname('magicuselog')." WHERE uid='$space[uid]' AND m\x69\144='gift' LIMIT 1"); if($value = $_SGLOBAL['db']->fetch_array($query)) { $data = empty($value['data'])?array():unserialize($value['data']); if($data['left'] <= 0) { $_SGLOBAL['db']->query('DELETE FROM '.tname('magicuselog')." WHERE uid = '$_SGLOBAL[supe_uid]' AND mi\144 = 'gift'"); } if(!$data['receiver'] || !in_array($_SGLOBAL['supe_uid'], $data['receiver'])) { $space['magiccredit'] = $data['left'] >= $data['chunk'] ? $data['chunk'] : $data['left']; } } }  
$ols = array(); if($oluids) { $query = $_SGLOBAL['db']->query("S\105L\105\x43\124 * F\x52\x4f\115 ".tname('session')." WHERE uid IN (".simplode($oluids).")"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { if(!$value['magichidden']) { $ols[$value['uid']] = 1; } elseif($visitorlist[$value['uid']]) { unset($visitorlist[$value['uid']]); } } }  
$narrowlist = $widelist = $guidelist = $space['userapp'] = array(); if ($_SCONFIG['my_status']) { $query = $_SGLOBAL['db']->query("\123EL\105\103\x54 m\141\151\156.*, fi\145\x6c\x64.*
		\x46\122\117\x4d ".tname('userapp')." m\x61\151n
		LEFT JOIN ".tname('userappfield')." fi\x65l\x64
		\117\x4e \146ie\x6cd.uid=\155\x61\151\156.uid AND f\151\x65\x6c\144.appid=\155\x61\x69\x6e.appid
		WHERE \x6da\151\x6e.uid='$space[uid]'
		ORDER BY \155\141\x69\156.displayorder DESC"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { $space['userapp'][$value['appid']] = $value; } } if($space['userapp']) { include_once(S_ROOT.'./source/function_userapp.php'); foreach ($space['userapp'] as $value) { if($value['allowprofilelink'] && $value['profilelink']) { $guidelist[] = $value; } if(app_ckprivacy($value['privacy']) && $value['myml']) { $value['appurl'] = 'userapp.php?id='.$value['appid']; if($value['narrow']) { $narrowlist[] = $value; } else { $widelist[] = $value; } } } }  
realname_get();  
foreach ($feedlist as $key => $value) { $feedlist[$key] = mkfeed($value); }  
if(!$space['self'] && $_SGLOBAL['supe_uid']) { include_once(S_ROOT.'./source/function_cp.php'); addfriendnum($space['uid'], $space['username']); }  
$_SGLOBAL['ad'] = array(); $_GET['view'] = 'me'; $_TPL['css'] = 'space'; include_once template("space_index");  
function show_credit() { global $_SGLOBAL, $space; $showcredit = getcount('show', array('uid'=>$space['uid']), 'credit'); if($showcredit>0) { if($showcredit == 1) {  
notification_add($space['uid'], 'show', cplang('note_show_out')); } $_SGLOBAL['db']->query("UPDATE ".tname('show')." SET credit=credit-1 WHERE uid='$space[uid]' AND credit>0"); } } ; ?>
