<?php   if(!defined('IN_UCHOME')) { exit('Access Denied'); } @include_once(S_ROOT.'./wap/data/data_profield.php'); $page = empty($_GET['page'])?1:intval($_GET['page']); if($page<1) $page=1; $id = empty($_GET['id'])?0:intval($_GET['id']); $tagid = empty($_GET['tagid'])?0:intval($_GET['tagid']); $fieldid = empty($_GET['fieldid'])?0:intval($_GET['fieldid']); $tagname = trim($_GET['tagname']);  
if($tagname) { $fields = array(); foreach ($_SGLOBAL['profield'] as $value) { if($value['formtype'] == 'text') { $fields[] = $value; 
} } $taglist = array(); if($fieldid) { $plussql = " AND fieldid='$fieldid'"; $field = $_SGLOBAL['profield'][$fieldid]; } else { $plussql = ''; $field = array(); } $query = $_SGLOBAL['db']->query("\x53\x45\x4c\x45CT * \x46\122O\115 ".tname('mtag')." WHERE tagname='$tagname' $plussql"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { $taglist[] = $value; } if(empty($taglist)) {  
$allowmk = 0; if($field && $field['formtype'] != 'text') { $query = $_SGLOBAL['db']->query("\123E\114\105C\124 * \x46\x52\x4f\115 ".tname('profield')." WHERE fieldid='$fieldid'"); if($field = $_SGLOBAL['db']->fetch_array($query)) { $field['choice'] = explode("\n", $field['choice']); $s = stripslashes($tagname); foreach ($field['choice'] as $subkey => $subvalue) { $subvalue = trim($subvalue); if($s == $subvalue) {  
$mtag = array( 'tagname' => addslashes($s), 'fieldid' => $fieldid ); $tagid = inserttable('mtag', $mtag, 1); showmessage('do_sucess', "space.\x70\150\160?\144\x6f=mtag&tagid=".$tagid, 0); } } } } elseif ($fields) { $allowmk = 1; } if(!$allowmk) { showmessage('mtag_creat_error'); } } elseif(count($taglist) == 1) {  
showmessage('do_sucess', "space.php?do=mtag&tagid=".$taglist[0]['tagid'], 0); } $_TPL['css'] = 'thread'; include_once template("space_mtag_tagname"); } elseif($id) { $perpage = 10; $start = ($page-1)*$perpage;  
ckstart($start, $perpage);  
$list = array(); $count = $_SGLOBAL['db']->result($_SGLOBAL['db']->query("\x53\105\x4c\105\x43\x54 COUNT(*) FR\117M ".tname('mtag')." WHERE fieldid='$id'"),0); if($count) { $query = $_SGLOBAL['db']->query("\x53E\114\x45C\x54 * \106\122O\x4d ".tname('mtag')." WHERE fieldid='$id' ORDER BY membernum DESC LIMIT $start,$perpage"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { if(empty($value['pic'])) { $value['pic'] = 'image/nologo.jpg'; } $list[] = $value; } }  
$multi = multi($count, $perpage, $page, "space.php?uid=$space[uid]&d\157=mtag&id=$id"); $fieldtitle = $_SGLOBAL['profield'][$id]['title']; $sub_actives = array($id => ' class="active"'); $fieldids = array($id => ' selected'); $_TPL['css'] = 'thread'; include_once template("space_mtag_field"); } elseif($tagid) { $actives = array($_GET['view'] => ' class="active"');  
$mtag = getmtag($tagid); if($mtag['close']) { showmessage('mtag_close'); }  
$eventnum = $_SGLOBAL['db']->result($_SGLOBAL['db']->query("\x53\x45\x4cE\x43\124 COUNT(*) FRO\115 ".tname("event")." WHERE tagid='$tagid'"), 0); if($_GET['view'] == 'list' || $_GET['view'] == 'digest') { $perpage = 10; $start = ($page-1)*$perpage;  
ckstart($start, $perpage); $theurl = "space.p\x68\x70?uid=$space[uid]&\144o=mtag&tagid=$tagid&view=$_GET[view]"; $wheresql = ($_GET['view'] == 'list')?'':" AND \155a\x69n.digest='1'"; if($searchkey = stripsearchkey($_GET['searchkey'])) { $wheresql .= "AND m\x61\151n.subject LIKE '%$searchkey%' "; $theurl .= "&searchkey=$_GET[searchkey]"; } $list = array(); $count = 0; if($mtag['allowview']) { $count = $_SGLOBAL['db']->result($_SGLOBAL['db']->query("S\x45\x4c\105\x43\x54 COUNT(*) \106R\117\x4d ".tname('thread')." m\141\x69n WHERE \155\x61\151n.tagid='$tagid' $wheresql"),0); if($count) { $query = $_SGLOBAL['db']->query("S\x45\114\x45\x43\124 \x6d\141i\x6e.* \x46\122\x4f\115 ".tname('thread')." \155\141\151\x6e 
					WHERE \155a\x69\156.tagid='$tagid' $wheresql
					ORDER BY m\x61in.displayorder DESC, \155\141i\x6e.lastpost DESC 
					LIMIT $start,$perpage"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['uid'], $value['username']); realname_set($value['lastauthorid'], $value['lastauthor']); $list[] = $value; } }  
$multi = multi($count, $perpage, $page, $theurl); realname_get(); } $_TPL['css'] = 'thread'; include_once template("space_mtag_list"); } elseif($_GET['view'] == 'member') { $perpage = 10; $start = ($page-1)*$perpage;  
ckstart($start, $perpage);  
$wheresql = ''; $_GET['key'] = stripsearchkey($_GET['key']); if($_GET['key']) { $wheresql = " AND \155\x61\151n.username LIKE '%$_GET[key]%' "; } $list = $fuids = array(); $count = 0; if($mtag['allowview']) { $count = $_SGLOBAL['db']->result($_SGLOBAL['db']->query("SELE\x43\x54 COUNT(*) F\122OM ".tname('tagspace')." \155\141\151\x6e WHERE m\x61\x69\156.tagid='$tagid' $wheresql"),0); if($count) { $query = $_SGLOBAL['db']->query("\123\105\114\105C\x54 f\x69\x65\154\144.*, \155\x61\x69\x6e.username, mai\156.grade F\x52\x4f\x4d ".tname('tagspace')." m\x61i\x6e 
					LEFT JOIN ".tname('spacefield')." f\151\x65\x6cd \x4f\x4e \146\x69\145ld.uid=main.uid 
					WHERE m\x61\151\x6e.tagid='$tagid' $wheresql ORDER BY m\x61\x69\156.grade DESC LIMIT $start,$perpage"); while ($value = $_SGLOBAL['db']->fetch_array($query)) {  
realname_set($value['uid'], $value['username']); $value['p'] = rawurlencode($value['resideprovince']); $value['c'] = rawurlencode($value['residecity']); $fuids[] = $value['uid']; $list[] = $value; } }  
$ols = array(); if($fuids) { $query = $_SGLOBAL['db']->query("S\105\x4c\105\103\124 * \106R\x4f\115 ".tname('session')." WHERE uid IN (".simplode($fuids).")"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { if(!$value['magichidden']) { $ols[$value['uid']] = $value['lastactivity']; } } }  
$multi = multi($count, $perpage, $page, "space.\x70\150\160?uid=$space[uid]&\144o=mtag&tagid=$tagid&view=member");  
realname_get(); } $_TPL['css'] = 'thread'; include_once template("space_mtag_member"); } elseif ($_GET['view'] == 'event') { $perpage = 10; $start = ($page-1)*$perpage;  
ckstart($start, $perpage); $eventlist = array(); if($eventnum) {  
@include_once(S_ROOT.'./data/data_eventclass.php'); $query = $_SGLOBAL['db']->query("S\105\x4cE\x43T * FR\117M ".tname("event")." WHERE tagid='$tagid' ORDER BY eventid DESC LIMIT $start, $perpage"); while($value=$_SGLOBAL['db']->fetch_array($query)) { if($value['poster']){ $value['pic'] = pic_get($value['poster'], $value['thumb'], $value['remote']); } else { $value['pic'] = $_SGLOBAL['eventclass'][$value['classid']]['poster']; } $eventlist[] = $value; } }  
$multi = multi($eventnum, $perpage, $page, "space.p\x68p?uid=$space[uid]&d\x6f=mtag&tagid=$tagid&view=event"); $_TPL['css'] = 'thread'; include_once template("space_mtag_event"); } else {  
$list = $starlist = $modlist = $memberlist = $checklist = array(); if($mtag['allowview']) { $query = $_SGLOBAL['db']->query("\123\105\x4c\105\103\x54 \x6d\141i\156.* \106ROM ".tname('thread')." \x6d\x61i\x6e 
				WHERE m\141\x69n.tagid='$tagid' 
				ORDER BY ma\x69n.displayorder DESC, \x6da\x69n.lastpost DESC 
				LIMIT 0,50"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['uid'], $value['username']); realname_set($value['lastauthorid'], $value['lastauthor']); $list[] = $value; }  
$query = $_SGLOBAL['db']->query("\x53\105\114\105\x43\124 * \x46\122O\x4d ".tname('tagspace')." WHERE tagid='$tagid' AND grade='1'"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['uid'], $value['username']); $starlist[] = $value; } $starlist = sarray_rand($starlist, 12); 
 
$query = $_SGLOBAL['db']->query("\123E\114E\x43\x54 * \x46\x52\117M ".tname('tagspace')." WHERE tagid='$tagid' AND grade='0' LIMIT 0,12"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['uid'], $value['username']); $memberlist[] = $value; } }  
$query = $_SGLOBAL['db']->query("\x53\105L\x45CT * F\x52\x4fM ".tname('tagspace')." WHERE tagid='$tagid' AND grade>'7' ORDER BY grade DESC LIMIT 0,12"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['uid'], $value['username']); $modlist[] = $value; }  
if($mtag['grade']>=8) {  
$query = $_SGLOBAL['db']->query("\123\x45\114\x45\103\124 * \106\122\117M ".tname('tagspace')." WHERE tagid='$tagid' AND grade='-2' LIMIT 0,12"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['uid'], $value['username']); $checklist[] = $value; } } realname_get(); $_TPL['css'] = 'thread'; include_once template("space_mtag_index"); } } else { $theurl = "space.\160\150\x70?uid=$space[uid]&d\x6f=mtag"; if(empty($_GET['view'])) $_GET['view'] = 'me'; if(!in_array($_GET['view'], array('me', 'hot', 'recommend', 'manage'))) $_GET['view'] = 'hot'; $theurl .= "&view=$_GET[view]"; $actives = array($_GET['view'] => ' class="active"'); $wherearr = array();  
if (!in_array($_GET['orderby'], array('threadnum', 'postnum', 'membernum'))) { $_GET['orderby'] = 'threadnum'; } else { $theurl .= "&orderby=$_GET[orderby]"; } $orderbyarr = array($_GET['orderby'] => ' class="active"');  
$_GET['fieldid'] = intval($_GET['fieldid']); if($_GET['fieldid']) { $wherearr[] = "mt.fieldid='$_GET[fieldid]'"; $theurl .= "&fieldid=$_GET[fieldid]"; $pro_actives = array($_GET['fieldid'] => ' class="current"'); } else { $pro_actives = array('all' => ' class="current"'); } $list = $rlist = array(); $multi = ''; $count = 0; $perpage = 10; $page = intval($_GET['page']); if($page < 1) $page = 1; $start = ($page-1)*$perpage; if($_GET['view'] == 'me' || $_GET['view'] == 'manage') { $sqlplus = $_GET['view'] == 'manage'?' AND main.grade=\'9\'':''; if($_GET['fieldid']) { $countsql = "S\x45L\x45\x43\x54 COUNT(*) \106RO\x4d ".tname('tagspace')." m\141\x69\x6e, ".tname('mtag')." mt
				WHERE \x6d\141\x69n.uid='$space[uid]' $sqlplus AND mt.tagid=\155\x61in.tagid AND ".implode(' AND ', $wherearr); $sql = "\x53E\114\105C\x54 \155\141\151\x6e.*,mt.* \106R\x4fM ".tname('tagspace')." \x6dai\x6e, ".tname('mtag')." mt
				WHERE \155\141\151\156.uid='$space[uid]' $sqlplus AND mt.tagid=\155a\151\x6e.tagid AND ".implode(' AND ', $wherearr)." ORDER BY mt.{$_GET['orderby']} DESC LIMIT $start,$perpage"; } else { $countsql = "\123\x45\x4c\x45\x43T COUNT(*) \106\122\117\115 ".tname('tagspace')." \x6d\141\151n
				WHERE \155a\x69n.uid='$space[uid]' $sqlplus"; $sql = "\123\x45\114E\x43\x54 \x6d\x61in.*,mt.* \x46\x52\117\115 ".tname('tagspace')." ma\151n 
				LEFT JOIN ".tname('mtag')." mt ON mt.tagid=\155\x61\x69\x6e.tagid
				WHERE \x6da\151\156.uid='$space[uid]' $sqlplus ORDER BY mt.{$_GET['orderby']} DESC LIMIT $start,$perpage"; } } else { if($_GET['view'] == 'recommend') { $wherearr[] = "mt.recommend='1'"; }  
if($searchkey = stripsearchkey($_GET['searchkey'])) { $wherearr[] = "mt.tagname LIKE '%$searchkey%'"; $theurl .= "&searchkey=$_GET[searchkey]"; } $countsql = "SE\114\x45\103\x54 COUNT(*) \x46\x52OM ".tname('mtag')." mt WHERE ".(empty($wherearr)?'1':implode(' AND ', $wherearr)); $sql = "\123\x45\x4c\x45CT mt.* F\x52OM ".tname('mtag')." mt
			WHERE ".(empty($wherearr)?'1':implode(' AND ', $wherearr))." ORDER BY mt.{$_GET['orderby']} DESC LIMIT $start,$perpage"; } $tagids = $tagnames = array(); $count = $_SGLOBAL['db']->result($_SGLOBAL['db']->query($countsql), 0); if($count) { $query = $_SGLOBAL['db']->query($sql); while ($value = $_SGLOBAL['db']->fetch_array($query)) { $value['title'] = $_SGLOBAL['profield'][$value['fieldid']]['title']; if(empty($value['pic'])) $value['pic'] = 'image/nologo.jpg'; $tagids[] = $value['tagid']; $tagnames[$value['tagid']] = $value['tagname']; $list[] = $value; } $multi = multi($count, $perpage, $page, $theurl); } $threadlist = array(); if($tagids) { $query = $_SGLOBAL['db']->query("\x53\x45\114\105C\124 * \106R\x4fM ".tname('thread')." WHERE tagid IN (".simplode($tagids).") ORDER BY dateline DESC LIMIT 0,10"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['uid'], $value['username']); realname_set($value['lastauthorid'], $value['lastauthor']); $value['tagname'] = getstr($tagnames[$value['tagid']], 20); $threadlist[] = $value; } } $_TPL['css'] = 'thread'; include_once template("space_mtag"); } ; ?>
